name: Android CI

on:
  push:
    branches:
      - 'main'
      - 'dev'
      - 'feature/study-ci'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
      # gradlew 권한 획득
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Generate Release Note
        run: |
          ./gradlew --version
          ./gradlew generateReleaseNote --stacktrace
