name: Android CI

on:
  push:
    branches:
      - 'main'
      - 'dev'
      - 'feature/study-ci'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: feature/study-ci

      # JDK 설정
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          check-latest: true

      # Dependency 에 버전 및 릴리즈 메시지 가져오기
      - name: Release Version
        id: release
        run: |
          echo ::set-output name=code::$(grep versionCode buildSrc/src/main/java/Dependency.kt | awk '{print $5}')
          echo ::set-output name=name::$(grep versionName buildSrc/src/main/java/Dependency.kt | awk '{print $5}')
          echo ::set-output name=message::$(sed -n '/Title/p' widget/release_message.txt)
          echo ::set-output name=message::$(sed -n '/Message/,$p' widget/release_message.txt | less)

      - name: Get Tag Name
        id: get_tag
        run: echo ::set-output name=name::${{steps.release.outputs.name}}

      # 릴리즈 생성
      # release_name: 릴리즈 제목
      # tag_name: 버전 이름
      # body: 릴리즈 메시지 내용
      - name: Generate Release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_name: ${{steps.release.outputs.title}}
          tag_name: ${{steps.get_tag.outputs.name}}
          body: |
            ${{steps.release.outputs.message}}
          draft: false
          prerelease: false

      # Android SDK 설정
      # - name: SetUp Android SDK
      #  uses: android-actions/setup-android@v2

      # gradlew 권한 획득
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew



      # 릴리즈 노트 작성
      # - name: Generate Release Note
      #   run: |
      #    ./gradlew generateReleaseNote --stacktrace
