name: Custom Build

on:
  issues:
    types: [labeled]
  
jobs:
  run_if_label_matches:
    ## 'custom_release' 라벨에서만 동작 하도록
    if: github.event.label.name == 'custom_release'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
#       - name: Event Info Print
#         id: IssueBody
#         run: |
#           echo ::set-output Event11Info ${{ github.event.issue.body }}
      - name: Generate Branch Name And Build Type
        id: generate
        run: |
          BODY=${{ github.event.issue.body }}
          echo ::set-output name=branch::$(grep branch: BODY | awk '{print $2}')
          echo ::set-output name=buildType::$(grep buildType: BODY | awk '{print $2}')
      - name: Build Print
        run: |
          echo ::set-output BranchName ${{ steps.generate.outputs.branch }}
          echo ::set-output BuildType ${{ steps.generate.outputs.buildType }}
