name: Custom Build

on:
  issues:
    types: [labeled,reopened]
  
jobs:
  run_if_label_matches:
    ## 'custom_release' 라벨에서만 동작 하도록
    if: github.event.label.name == 'custom_release'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Issue Body
        id: body
        run: |
         echo ::set-output name=val::"${{ github.event.issue.body }}"
      - name: Generate Branch Name And Build Type
        id: generate
        run: |
          echo ::set-output $(grep branch: steps.body.val awk '{print $2}' )
          echo ::set-output $(grep buildType: steps.body.val awk '{print $2}' )
      - name: Build Print
        run: |
          echo ::set-output BranchName ${{ steps.generate.outputs.branch }}
          echo ::set-output BuildType ${{ steps.generate.outputs.buildType }}
