name: Custom Build

on:
  issues:
    types: [labeled,reopened]
  
jobs:
  run_if_label_matches:
    ## 'custom_release' 라벨에서만 동작 하도록
    if: github.event.label.name == 'custom_release'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Issue Body
        id: body
        run: |
          echo "${{ github.event.issue.body }}" >> buildInfo.txt

      - name: Generate Branch Name And Build Type
        id: generate
        run: |
          echo ::set-output name=buildBranch::$(grep branchName: buildInfo.txt | awk '{print $1}' )
          echo ::set-output name=buildType::$(grep buildType: buildInfo.txt | awk '{print $1}' )
      - name: Build Print
        run: |
          echo ::set-output BranchName ${{ steps.generate.outputs.branchName }}
          echo ::set-output BuildType ${{ steps.generate.outputs.buildType }}
