name: Custom Build

on:
  issues:
    types: [labeled]
  
jobs:
  run_if_label_matches:
    ## 'custom_release' 라벨에서만 동작 하도록
    if: github.event.label.name == 'custom_release'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Event Info Print
        id: test
        run: |
          echo ::set-output Event11Info ${{ github.event.issue.body }}
          echo ::set-output Event22 ${{ github.event.issue.name }}
          echo ::set-output Event33 ${{ github.event.issue }}
