name: Custom Build

on:
  issues:
    types: [labeled,reopened]
  
jobs:
  run_if_label_matches:
    ## 'custom_release' 라벨에서만 동작 하도록
    if: github.event.label.name == 'custom_release'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Event Info Print
        id: body
        run: |
          BODY=$(github.event.issue.body)
          BDOY="${BDOY//'%'/'%25'}"
          BODY="${BDOY//$'\n'/'%0A'}"
          BODY="${BDOY//$'\r'/'%0D'}"
          echo ::set-output name=val::${BODY}
      - name: Generate Branch Name And Build Type
        id: generate
        run: |
          echo ::set-output $( steps.body.val awk '{print $1}' )
          
      - name: Build Print
        run: |
          echo ::set-output BranchName ${{ steps.generate.outputs.branch }}
          echo ::set-output BuildType ${{ steps.generate.outputs.buildType }}
