name: Custom Build

on:
  issues:
    types: [labeled,reopened]
  
jobs:
  run_if_label_matches:
      ## 'custom_release' 라벨에서만 동작 하도록
      if: github.event.label.name == 'custom_release'
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v2
        - name: Issue Body
          id: body
          run: |
            echo "${{ github.event.issue.body }}" >> buildInfo.txt

        - name: Generate Branch Name And Build Type
          id: build
          run: |
            echo ::set-output name=branchName::$(grep branchName: buildInfo.txt | awk '{print $2}' )
            echo ::set-output name=type::$(grep buildType: buildInfo.txt | awk '{print $2}' )
        
        - name: Build Print
          run: |
            echo ::set-output BranchName ${{ steps.build.outputs.branchName }}
            echo ::set-output BuildType ${{ steps.build.outputs.type }}
        
        - name: Set Environments
          env: |
            BRANCH_NAME: ${{ steps.build.outputs.branchName }}
            BUILD_TYPE: ${{ steps.build.outputs.type }}
          run: echo $BRANCH_NAME , $BUILD_TYPE
        
  buildJobs:
    runs-on: ubuntu-latest
    
    # 위에서 데이터 가져옴
    needs: run_if_label_matches
    
    steps:
      - name: BuildName
        run: |
          echo Test $BRANCH_NAME , $BUILD_TYPE
    
