name: Custom Build

on:
  label: {custom_release}
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2


      - name: Test Issue Label
        id: test
        run: |
          echo ::set-output heelllooo
