name: develop-TEST

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
          check-latest: true
      
      - name: Get Current Date
        id: date
        run: echo "::set-output name=date::$(date + '%Y-%m-%d')"
      
      - name: Build Release
        run: bash ./gradlew clean assembleRelease
        
        
