name: Upload APK
on:
  workflow_dispatch:

jobs:
  build-and-upload-apk:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # JDK 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      # Android SDK 설정
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      # Gradle 캐시 설정 (빌드 속도 향상)
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # gradlew 실행 권한 부여
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 버전 정보 가져오기 (app/build.gradle에서 versionName 추출)
      - name: Get Version Name
        id: get_version
        run: |
          version="1.0.0"  # 기본값
          
          if [ -f "app/build.gradle" ]; then
            echo "=== app/build.gradle에서 versionName 찾기 ==="
          
            # versionName 라인 찾기
            version_line=$(grep "versionName" app/build.gradle)
            echo "versionName 라인: $version_line"
          
            # 여러 패턴으로 추출 시도
            if [[ "$version_line" =~ versionName[[:space:]]*[\"\']*([0-9]+\.[0-9]+\.[0-9]+)[\"\']*$ ]]; then
              version="${BASH_REMATCH[1]}"
              echo "직접 버전 패턴으로 추출: $version"
            elif [[ "$version_line" =~ versionName[[:space:]]*[\"\']([^\"\']+)[\"\'] ]]; then
              version="${BASH_REMATCH[1]}"
              echo "따옴표 패턴으로 추출: $version"
            else
              # sed로 추출
              version=$(echo "$version_line" | sed -E 's/.*versionName[[:space:]]*["\']([^"\']+)["\'].*/\1/')
              echo "sed로 추출: $version"
            fi
          else
            echo "app/build.gradle 파일을 찾을 수 없습니다."
          fi
          
          # 버전이 비어있거나 잘못된 경우 기본값 사용
          if [ -z "$version" ] || [ "$version" = "$version_line" ]; then
            version="1.0.0"
            echo "추출 실패, 기본값 사용: $version"
          fi
          
          echo "version=$version" >> $GITHUB_OUTPUT
          echo "최종 추출된 버전: '$version'"

      # APK 빌드
      - name: Build Release APK
        run: ./gradlew assembleRelease --stacktrace

      # 빌드된 APK 파일 확인
      - name: List built APK files
        run: |
          echo "=== 빌드된 APK 파일 목록 ==="
          find . -name "*.apk" -type f
          echo "=========================="

      # apk 디렉토리 생성
      - name: Create APK directory
        run: mkdir -p apk

      # APK 파일을 apk 디렉토리로 복사
      - name: Copy APK to apk directory
        run: |
          echo "APK 파일을 apk/ 디렉토리로 복사 중..."
          
          # 기존 APK 파일 정리
          rm -f apk/*.apk 2>/dev/null || true
          
          # APK 파일 찾기 및 복사
          find . -name "*.apk" -path "*/build/outputs/apk/release/*" -exec cp {} apk/ \;
          
          # 복사된 파일 확인
          echo "=== 복사 후 apk/ 디렉토리 내용 ==="
          ls -la apk/
          
          # widget_{versionName}_{timestamp} 형식으로 파일명 변경
          cd apk
          version_name="${{ steps.get_version.outputs.version }}"
          timestamp=$(date +"%Y%m%d_%H%M")
          
          echo "사용할 버전: '$version_name'"
          echo "사용할 타임스탬프: '$timestamp'"
          
          for file in *.apk; do
            if [ -f "$file" ] && [ "$file" != "*.apk" ]; then
              new_name="widget_${version_name}_${timestamp}.apk"
              mv "$file" "$new_name"
              echo "파일명 변경: $file -> $new_name"
            fi
          done
          
          echo "=== 파일명 변경 후 내용 ==="
          ls -la

      # Git 설정 및 APK 파일 커밋
      - name: Commit and push APK
        run: |
          # Git 사용자 정보 설정
          git config --local user.email "upload-bot@github.com"
          git config --local user.name "upload-bot"
          
          # APK 파일 추가
          git add apk/*.apk
          
          # 변경사항이 있는지 확인
          if git diff --staged --quiet; then
            echo "커밋할 변경사항이 없습니다."
          else
            # 커밋 및 푸시
            commit_message="Add widget APK v${{ steps.get_version.outputs.version }} - $(date '+%Y-%m-%d %H:%M')"
            git commit -m "$commit_message"
            git push
            echo "APK 파일이 성공적으로 업로드되었습니다!"
          fi

      # 결과 확인
      - name: Verify upload
        run: |
          echo "=== 최종 apk/ 디렉토리 내용 ==="
          ls -la apk/
          echo "================================"